/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorialRouteImport } from './routes/editorial'
import { Route as FestivalRouteImport } from './routes/festival'
import { Route as EditorialIndexRouteImport } from './routes/editorial.index'
import { Route as EditorialArchivoRouteImport } from './routes/editorial.archivo'
import { Route as EditorialCatalogoRouteImport } from './routes/editorial.catalogo'
import { Route as EditorialContactoRouteImport } from './routes/editorial.contacto'
import { Route as EditorialManifiestoRouteImport } from './routes/editorial.manifiesto'
import { Route as EditorialPortafolioRouteImport } from './routes/editorial.portafolio'
import { Route as FestivalIndexRouteImport } from './routes/festival.index'
import { Route as FestivalArchivoRouteImport } from './routes/festival.archivo'
import { Route as FestivalFipq21RouteImport } from './routes/festival.fipq21'
import { Route as FestivalGaleriaRouteImport } from './routes/festival.galeria'
import { Route as FestivalManifiestoRouteImport } from './routes/festival.manifiesto'
import { Route as FestivalProgramaRouteImport } from './routes/festival.programa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialRoute = EditorialRouteImport.update({
  id: '/editorial',
  path: '/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalRoute = FestivalRouteImport.update({
  id: '/festival',
  path: '/festival',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialIndexRoute = EditorialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorialRoute,
} as any)
const EditorialArchivoRoute = EditorialArchivoRouteImport.update({
  id: '/archivo',
  path: '/archivo',
  getParentRoute: () => EditorialRoute,
} as any)
const EditorialCatalogoRoute = EditorialCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => EditorialRoute,
} as any)
const EditorialContactoRoute = EditorialContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => EditorialRoute,
} as any)
const EditorialManifiestoRoute = EditorialManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => EditorialRoute,
} as any)
const EditorialPortafolioRoute = EditorialPortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => EditorialRoute,
} as any)
const FestivalIndexRoute = FestivalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FestivalRoute,
} as any)
const FestivalArchivoRoute = FestivalArchivoRouteImport.update({
  id: '/archivo',
  path: '/archivo',
  getParentRoute: () => FestivalRoute,
} as any)
const FestivalFipq21Route = FestivalFipq21RouteImport.update({
  id: '/fipq21',
  path: '/fipq21',
  getParentRoute: () => FestivalRoute,
} as any)
const FestivalGaleriaRoute = FestivalGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => FestivalRoute,
} as any)
const FestivalManifiestoRoute = FestivalManifiestoRouteImport.update({
  id: '/manifiesto',
  path: '/manifiesto',
  getParentRoute: () => FestivalRoute,
} as any)
const FestivalProgramaRoute = FestivalProgramaRouteImport.update({
  id: '/programa',
  path: '/programa',
  getParentRoute: () => FestivalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editorial': typeof EditorialRouteWithChildren
  '/festival': typeof FestivalRouteWithChildren
  '/editorial/archivo': typeof EditorialArchivoRoute
  '/editorial/catalogo': typeof EditorialCatalogoRoute
  '/editorial/contacto': typeof EditorialContactoRoute
  '/editorial/manifiesto': typeof EditorialManifiestoRoute
  '/editorial/portafolio': typeof EditorialPortafolioRoute
  '/festival/archivo': typeof FestivalArchivoRoute
  '/festival/fipq21': typeof FestivalFipq21Route
  '/festival/galeria': typeof FestivalGaleriaRoute
  '/festival/manifiesto': typeof FestivalManifiestoRoute
  '/festival/programa': typeof FestivalProgramaRoute
  '/editorial/': typeof EditorialIndexRoute
  '/festival/': typeof FestivalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editorial/archivo': typeof EditorialArchivoRoute
  '/editorial/catalogo': typeof EditorialCatalogoRoute
  '/editorial/contacto': typeof EditorialContactoRoute
  '/editorial/manifiesto': typeof EditorialManifiestoRoute
  '/editorial/portafolio': typeof EditorialPortafolioRoute
  '/festival/archivo': typeof FestivalArchivoRoute
  '/festival/fipq21': typeof FestivalFipq21Route
  '/festival/galeria': typeof FestivalGaleriaRoute
  '/festival/manifiesto': typeof FestivalManifiestoRoute
  '/festival/programa': typeof FestivalProgramaRoute
  '/editorial': typeof EditorialIndexRoute
  '/festival': typeof FestivalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editorial': typeof EditorialRouteWithChildren
  '/festival': typeof FestivalRouteWithChildren
  '/editorial/archivo': typeof EditorialArchivoRoute
  '/editorial/catalogo': typeof EditorialCatalogoRoute
  '/editorial/contacto': typeof EditorialContactoRoute
  '/editorial/manifiesto': typeof EditorialManifiestoRoute
  '/editorial/portafolio': typeof EditorialPortafolioRoute
  '/festival/archivo': typeof FestivalArchivoRoute
  '/festival/fipq21': typeof FestivalFipq21Route
  '/festival/galeria': typeof FestivalGaleriaRoute
  '/festival/manifiesto': typeof FestivalManifiestoRoute
  '/festival/programa': typeof FestivalProgramaRoute
  '/editorial/': typeof EditorialIndexRoute
  '/festival/': typeof FestivalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editorial'
    | '/festival'
    | '/editorial/archivo'
    | '/editorial/catalogo'
    | '/editorial/contacto'
    | '/editorial/manifiesto'
    | '/editorial/portafolio'
    | '/festival/archivo'
    | '/festival/fipq21'
    | '/festival/galeria'
    | '/festival/manifiesto'
    | '/festival/programa'
    | '/editorial/'
    | '/festival/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editorial/archivo'
    | '/editorial/catalogo'
    | '/editorial/contacto'
    | '/editorial/manifiesto'
    | '/editorial/portafolio'
    | '/festival/archivo'
    | '/festival/fipq21'
    | '/festival/galeria'
    | '/festival/manifiesto'
    | '/festival/programa'
    | '/editorial'
    | '/festival'
  id:
    | '__root__'
    | '/'
    | '/editorial'
    | '/festival'
    | '/editorial/archivo'
    | '/editorial/catalogo'
    | '/editorial/contacto'
    | '/editorial/manifiesto'
    | '/editorial/portafolio'
    | '/festival/archivo'
    | '/festival/fipq21'
    | '/festival/galeria'
    | '/festival/manifiesto'
    | '/festival/programa'
    | '/editorial/'
    | '/festival/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorialRoute: typeof EditorialRouteWithChildren
  FestivalRoute: typeof FestivalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial': {
      id: '/editorial'
      path: '/editorial'
      fullPath: '/editorial'
      preLoaderRoute: typeof EditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival': {
      id: '/festival'
      path: '/festival'
      fullPath: '/festival'
      preLoaderRoute: typeof FestivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/': {
      id: '/editorial/'
      path: '/'
      fullPath: '/editorial/'
      preLoaderRoute: typeof EditorialIndexRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/editorial/archivo': {
      id: '/editorial/archivo'
      path: '/archivo'
      fullPath: '/editorial/archivo'
      preLoaderRoute: typeof EditorialArchivoRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/editorial/catalogo': {
      id: '/editorial/catalogo'
      path: '/catalogo'
      fullPath: '/editorial/catalogo'
      preLoaderRoute: typeof EditorialCatalogoRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/editorial/contacto': {
      id: '/editorial/contacto'
      path: '/contacto'
      fullPath: '/editorial/contacto'
      preLoaderRoute: typeof EditorialContactoRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/editorial/manifiesto': {
      id: '/editorial/manifiesto'
      path: '/manifiesto'
      fullPath: '/editorial/manifiesto'
      preLoaderRoute: typeof EditorialManifiestoRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/editorial/portafolio': {
      id: '/editorial/portafolio'
      path: '/portafolio'
      fullPath: '/editorial/portafolio'
      preLoaderRoute: typeof EditorialPortafolioRouteImport
      parentRoute: typeof EditorialRoute
    }
    '/festival/': {
      id: '/festival/'
      path: '/'
      fullPath: '/festival/'
      preLoaderRoute: typeof FestivalIndexRouteImport
      parentRoute: typeof FestivalRoute
    }
    '/festival/archivo': {
      id: '/festival/archivo'
      path: '/archivo'
      fullPath: '/festival/archivo'
      preLoaderRoute: typeof FestivalArchivoRouteImport
      parentRoute: typeof FestivalRoute
    }
    '/festival/fipq21': {
      id: '/festival/fipq21'
      path: '/fipq21'
      fullPath: '/festival/fipq21'
      preLoaderRoute: typeof FestivalFipq21RouteImport
      parentRoute: typeof FestivalRoute
    }
    '/festival/galeria': {
      id: '/festival/galeria'
      path: '/galeria'
      fullPath: '/festival/galeria'
      preLoaderRoute: typeof FestivalGaleriaRouteImport
      parentRoute: typeof FestivalRoute
    }
    '/festival/manifiesto': {
      id: '/festival/manifiesto'
      path: '/manifiesto'
      fullPath: '/festival/manifiesto'
      preLoaderRoute: typeof FestivalManifiestoRouteImport
      parentRoute: typeof FestivalRoute
    }
    '/festival/programa': {
      id: '/festival/programa'
      path: '/programa'
      fullPath: '/festival/programa'
      preLoaderRoute: typeof FestivalProgramaRouteImport
      parentRoute: typeof FestivalRoute
    }
  }
}

interface EditorialRouteChildren {
  EditorialArchivoRoute: typeof EditorialArchivoRoute
  EditorialCatalogoRoute: typeof EditorialCatalogoRoute
  EditorialContactoRoute: typeof EditorialContactoRoute
  EditorialManifiestoRoute: typeof EditorialManifiestoRoute
  EditorialPortafolioRoute: typeof EditorialPortafolioRoute
  EditorialIndexRoute: typeof EditorialIndexRoute
}

const EditorialRouteChildren: EditorialRouteChildren = {
  EditorialArchivoRoute: EditorialArchivoRoute,
  EditorialCatalogoRoute: EditorialCatalogoRoute,
  EditorialContactoRoute: EditorialContactoRoute,
  EditorialManifiestoRoute: EditorialManifiestoRoute,
  EditorialPortafolioRoute: EditorialPortafolioRoute,
  EditorialIndexRoute: EditorialIndexRoute,
}

const EditorialRouteWithChildren = EditorialRoute._addFileChildren(
  EditorialRouteChildren,
)

interface FestivalRouteChildren {
  FestivalArchivoRoute: typeof FestivalArchivoRoute
  FestivalFipq21Route: typeof FestivalFipq21Route
  FestivalGaleriaRoute: typeof FestivalGaleriaRoute
  FestivalManifiestoRoute: typeof FestivalManifiestoRoute
  FestivalProgramaRoute: typeof FestivalProgramaRoute
  FestivalIndexRoute: typeof FestivalIndexRoute
}

const FestivalRouteChildren: FestivalRouteChildren = {
  FestivalArchivoRoute: FestivalArchivoRoute,
  FestivalFipq21Route: FestivalFipq21Route,
  FestivalGaleriaRoute: FestivalGaleriaRoute,
  FestivalManifiestoRoute: FestivalManifiestoRoute,
  FestivalProgramaRoute: FestivalProgramaRoute,
  FestivalIndexRoute: FestivalIndexRoute,
}

const FestivalRouteWithChildren = FestivalRoute._addFileChildren(
  FestivalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorialRoute: EditorialRouteWithChildren,
  FestivalRoute: FestivalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
